# Generated by Django 3.2.14 on 2022-08-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_coupon_usedcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedcoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='usedcoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='coupon',
        ),
        migrations.DeleteModel(
            name='usedcoupon',
        ),
    ]
