# Generated by Django 3.2.14 on 2022-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220801_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='is_applied',
            field=models.BooleanField(default=True),
        ),
    ]
