# Generated by Django 3.2.14 on 2022-07-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_categoryoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoryoffer',
        ),
    ]
