# Generated by Django 3.2.14 on 2022-07-28 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_delete_categoryoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='discount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
