# Generated by Django 3.2.14 on 2022-07-29 01:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20220729_0041'),
        ('carts', '0008_auto_20220728_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='valid_to',
        ),
        migrations.CreateModel(
            name='categoryoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats_offers', to='products.categories')),
            ],
        ),
    ]
