# Generated by Django 3.2.14 on 2022-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_coupon_couponuseduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='coupon_code',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='discount_price',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='couponUsedUser',
        ),
    ]
