# Generated by Django 3.2.14 on 2022-07-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_auto_20220729_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minium_amount',
            field=models.IntegerField(null=True),
        ),
    ]
