# Generated by Django 3.2.14 on 2022-08-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_couponuseduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='minium_amount',
        ),
    ]
