# Generated by Django 3.2.14 on 2022-08-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_remove_coupon_minium_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
