# Generated by Django 3.2.14 on 2022-08-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_rename_discount_price_coupon_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='active',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
