# Generated by Django 3.2.14 on 2022-08-03 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_delete_coupon'),
        ('carts', '0017_auto_20220803_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cats_offers', to='products.categories'),
        ),
    ]
