# Generated by Django 3.2.14 on 2022-07-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20220721_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.payment'),
        ),
    ]
