# Generated by Django 3.2.14 on 2022-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20220723_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order conformed', 'order Confirmed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returned', 'returned'), ('return_accepted', 'return_accepted')], default='order conformed', max_length=100, null=True),
        ),
    ]
