# Generated by Django 3.2.14 on 2022-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='product_status',
            field=models.CharField(choices=[('order conformed', 'order Confirmed'), ('shipped', 'shipped'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returned', 'returned'), ('return_accepted', 'return_accepted')], default='order conformed', max_length=100, null=True),
        ),
    ]
