# Generated by Django 3.2.14 on 2022-08-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
