# Generated by Django 3.2.14 on 2022-08-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
