# Generated by Django 4.0.5 on 2022-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300)),
                ('des', models.TextField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.CharField(max_length=3000),
        ),
    ]
