# Generated by Django 4.0.5 on 2022-07-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cat_delete_category_alter_products_cat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='products',
            name='cats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
    ]
