# Generated by Django 4.0.5 on 2022-07-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='price',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='stock',
        ),
    ]
