# Generated by Django 3.2.14 on 2022-07-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220707_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
    ]
