# Generated by Django 3.2.14 on 2022-07-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
    ]
