# Generated by Django 3.2.14 on 2022-07-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
