# Generated by Django 3.2.14 on 2022-07-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20220726_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.DeleteModel(
            name='categoryoffer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
