# Generated by Django 3.2.14 on 2022-07-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20220726_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='offer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='offerproduct',
            field=models.IntegerField(null=True),
        ),
    ]
