# Generated by Django 3.2.14 on 2022-07-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_new_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_new_price',
            field=models.IntegerField(null=True),
        ),
    ]
