# Generated by Django 3.2.14 on 2022-07-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_coupon_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category_new_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_new_price',
        ),
    ]
