# Generated by Django 3.2.14 on 2022-07-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_categories_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
