# Generated by Django 3.2.14 on 2022-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=3000, null=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
